### PR TITLE
Add test to make sure `features_and_tags.json` looks as expected

### PR DESCRIPTION
**Pull request by xylar**
This test generates a new `features_and_tags.json` based on the contents of `geometric_data`.

The contents of `geometric_features/features_and_tags.json` have been updated with the correct data produced with:
`geometric_features.utils.write_feature_names_and_tags()`.

### CODE REVIEW

**Comment by xylar** [comment]
@alexolinhager, I think there are several more things that need to be fixed in `features_and_tags.json` besides #217.  I have taken care of all of them here, but this PR is based off of #218 and #219 so leaving it in draft mode for now.

**Review by alexolinhager — APPROVED** [review]
@xylar, thanks for making these changes and adding the features and tags test. Makes sense to combine this all into one PR. Looks good to me

**Comment by xylar** [comment]
@alexolinhager, thanks for the review. Can I take this as an implicit approval of #218 and #219?

**Comment by alexolinhager** [comment]
@xylar, yes, that's fine by me

**Pull request merged**
