### PR TITLE
Improve testing and support shapely 2.0

### LINKED ISSUE #183: replace `pkg_resources` with `importlib.resources`
The former is not a built-in part of python, whereas the latter is a standard part of more recent versions of python.

### PR DESCRIPTION
**Pull request by xylar**
This merge updates the required `shapely` version to `>=2.0,<3.0` because of several changes in the shapely API.  In order to test whether `geometric_features` is working with `shapely` as expected, 28 new tests have been added that cover nearly all of the package's functionality (the `docs` module is tested separately when the documentation gets built).

Some other clean up was needed as well as a small bug fix along the way.

closes #183

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@xylar: do you want me to review this visually or by running a test?

**Comment by xylar** [comment]
@milenaveneziani, thanks for asking!  I think just giving it a look and making sure you don't see anything worrisome would be fine.  If you feel like running some tests, that's fine, too.  I tested pretty thoroughly in the process of adding the new CI tests, though, so you don't need to.

**Review by milenaveneziani — APPROVED** [review]
Approved by visual inspection and considering @xylar's thorough testing.

**Comment by xylar** [comment]
Thanks @milenaveneziani!

**Pull request merged**
