### PR TITLE
Add a script for setting up 6 ocean basins

### PR DESCRIPTION
**Pull request by xylar**
This merge adds a script that can be used to generate the 6 major ocean basins: Atlantic, Pacific, Indian, Mediterranean, Southern Ocean and Arctic.

Optionally, with the --plot flag, the results can be plotted.

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, hopefully this script satisfies your request for a driver script from #20.

**Comment by xylar** [comment]
@milenaveneziani, this one can be merged when you're ready.

**Comment by milenaveneziani** [comment]
@xylar : after merging this, I then tried to use the relevant script to make the basin plots (wanted to check what was in the Mediterranean Basin) and realized that there are 2 typos in the last 2 lines. On line 33, you should remove a 'd' and an indentation level. On line 34, there is just the extra indentation.

**Comment by xylar** [comment]
@milenaveneziani, thanks for pointing this out.  I have no idea how that happened.

I guess it points out that I was too hasty in my commit somehow.  It also points out that it's important that you, as the reviewer, do actually run the scripts and test them before fulfilling the pull request.

I'll make a new PR with a fix.

**Pull request merged**
