### PR TITLE
Sort properties before writing to geojson

### PR DESCRIPTION
**Pull request by xylar**
feature properties are placed in an ordered dictionary before
writing.  Keys other than type and groupName in feature collections
are also sorted, as are keys other than type and properties in
individual features.

### CODE REVIEW

**Comment by xylar** [comment]
This merge is intended to make sure geojson files remain bit-for-bit (at least to the extent possible).  By sorting properties, we are able to ensure that they will be written in the same order, previously the ordering of properties was arbitrary.

**Comment by xylar** [comment]
@pwolfram, I think this PR should take care of the non-bit-for-bit issue you were seeing.  Let me know if not.

**Comment by xylar** [comment]
@pwolfram, we could also make the geometry dictionary be an `OrderedDict` for completeness if you like.  It wouldn't be hard.  So far I haven't seen cases where it's an issue but there's no guarantee of bit-for-bit if we don't.  I guess I'll just go ahead and change it.

**Comment by pwolfram** [comment]
@xylar, could we please change `check_feature` to `_check_feature` to indicate it is a private function for this module?  As far as I can tell there is no planned usage for this function outside this module and it would make the code a little clearer.

**Comment by pwolfram** [comment]
Otherwise, this PR is great and I'm happy to merge.

**Comment by xylar** [comment]
@pwolfram, I just made a few changes, including your request from above.

I now make sure that "features" come last in a feature collection and "geometry" comes last in a feature.

**Comment by xylar** [comment]
flake8 seems to think the formatting is okay.

**Comment by xylar** [comment]
Off to bed...

**Comment by pwolfram** [comment]
@xylar, I made one small modification at https://github.com/pwolfram/geometric_features/tree/sort_geojson_keys that you can take or leave-- it basically just sorts properties in a more intuitive way setting the order of some properties.  Otherwise, I think this is good to merge.  If you like the change in commit `7fe4eedeb98111b07f0b7394c384ed676cc5395a`, please feel free to cherry-pick and squash.  This is great and looks good to me.  Thanks @xylar!

**Comment by xylar** [comment]
@pwolfram, yes, that makes sense.

**Comment by xylar** [comment]
We will need to redo #71 to be consistent with these changes.  I will do this as soon as this PR is merged.

**Comment by pwolfram** [comment]
Thanks @xylar!

**Pull request merged**
