### PR TITLE
Adds Travis CI and example tests

### PR DESCRIPTION
**Pull request by pwolfram**
This commit adds Travis CI capability and performs a simple unit test.

### CODE REVIEW

**Comment by xylar** [comment]
This looks good to me.  Is it ready to merge as far as you're concerned, @pwolfram?

**Comment by pwolfram** [comment]
Note, I refractored `set_group_name.py` and tested to make sure `driver_scripts/setup_ocean_region_groups.py` ran cleanly.

I think for simplicity this is ready to merge although we are obviously missing additional unit tests.  I'm happy to help add them in but I don't want to duplicate any effort you had planned so a discussion prior to doing this is probably in order.

**Comment by pwolfram** [comment]
Feel free to merge when you get a change @xylar!

**Comment by pwolfram** [comment]
Thanks!

**Pull request merged**
