### PR TITLE
Add ISMIP6 basins to landice regions

### PR DESCRIPTION
**Pull request by xylar**
This merge adds:
* a script for building the ISMIP6 basins
* a fix for splitting features at the antemeridian (needed for these new features to be valid)
* 16 regions for the ISMIP6 basins defined in [Jourdain et al. 2020](https://doi.org/10.5194/tc-14-3111-2020)

ISMIP6_basins

### CODE REVIEW

**Comment by xylar** [comment]
@hollyhan, this is ready to review.  A quick review would be just to look through the new features here on GitHub:
https://github.com/xylar/geometric_features/tree/add_ismip6_basins/geometric_data/landice/region
e.g.:
https://github.com/xylar/geometric_features/blob/add_ismip6_basins/geometric_data/landice/region/ISMIP6_Basin_A-Ap/region.geojson

A more thorough review would be if you run the feature creation script yourself.
```
mamba create -y -n geom_dev --file dev-spec.txt
conda activate geom_dev
python -m pip install -e .
mamba install ismip6-antarctic-ocean-forcing xarray pyproj
cd feature_creation_scripts/ismip6_landice_basins/
./basin_masks_to_geojson_regions.py
```
You may find running this script produces slight changes in the basins.  That's not a big deal as far as I'm concerned.  The plots should look the same.

After this, I'll need to make a release of `geometric_features` and we'll need to use that in your compass PR https://github.com/MPAS-Dev/compass/pull/406

**Comment by xylar** [comment]
@hollyhan, I made a simple test script that mimics how we will use this in your PR:
``` python
#!/usr/bin/env python

import matplotlib.pyplot as plt
from geometric_features import GeometricFeatures


gf = GeometricFeatures()
fc = gf.read('landice', 'region', tags=['ISMIP6_Basin'])
fc.plot('southpole')
plt.savefig('ISMIP6_basins.png')
```
Please try that out as well.

**Comment by hollyhan** [comment]
Thanks so much for getting this updated so quickly, @xylar!

My test passes with the resulting plot identical to what you posted above.
ISMIP6_basins

There are some deprecation warnings regarding the python `shapely` and download warning as follow, but everything works fine yet. 

```
/Users/hollyhan/miniconda3/envs/geom_dev/lib/python3.10/site-packages/ismip6_ocean_forcing/imbie/images.py:70: ShapelyDeprecationWarning: The 'cascaded_union()' function is deprecated. Use 'unary_union()' instead.
  combinedShape = shapely.ops.cascaded_union(featureShapes)
  Writing basin images...
    A-Ap
/Users/hollyhan/miniconda3/envs/geom_dev/lib/python3.10/site-packages/descartes/patch.py:62: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
/Users/hollyhan/Desktop/E3SM-Project/geometric_features/geometric_features/plot.py:126: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  for polygon in geometry:
/Users/hollyhan/miniconda3/envs/geom_dev/lib/python3.10/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naturalearth.s3.amazonaws.com/50m_physical/ne_50m_land.zip
  warnings.warn(f'Downloading: {url}', DownloadWarning)
```

**Comment by hollyhan** [comment]
> @hollyhan, I made a simple test script that mimics how we will use this in your PR:
> 
> ```python
> #!/usr/bin/env python
> 
> import matplotlib.pyplot as plt
> from geometric_features import GeometricFeatures
> 
> 
> gf = GeometricFeatures()
> fc = gf.read('landice', 'region', tags=['ISMIP6_Basin'])
> fc.plot('southpole')
> plt.savefig('ISMIP6_basins.png')
> ```
> 
> Please try that out as well.

@xylar, thanks for creating this sample script :). I've test it it by incorporating it in my PR, and I'm getting an error related to `shapely`. 
  File "/Users/hollyhan/Desktop/RESEARCH/MALI/compass/add_regionMask_AIS_meshGen/compass/landice/tests/antarctica/mesh.py", line 168, in run
    fc.plot('southpole')
  File "/Users/hollyhan/miniconda3/envs/compass_region_mask/lib/python3.9/site-packages/geometric_features/feature_collection.py", line 539, in plot
    box = shapely.geometry.box(*bounds)
TypeError: shapely.geometry.geo.box() argument after * must be an iterable, not NoneType
```
I also see that the region mask file for ismip6 created in my PR is somehow invalid unlike the one created for the imbie basin.
```
(compass_region_mask) pn2034311:mesh hollyhan$ ncdump -h ismip6_regionMasks.nc 
ncdump: ismip6_regionMasks.nc: NetCDF: NC_UNLIMITED in the wrong index
```
I'll look into it a bit more and bring it up if I haven't figured it out by our next meeting.  We can also move this conversation to my PR(https://github.com/MPAS-Dev/compass/pull/406).

**Review by hollyhan — APPROVED** [review]

**Comment by xylar** [comment]
@hollyhan I think I will hold off on merging this until you can try building the package again with this branch instead of master.  It would be a pain to find out only after releasing the next version of `geometric_features` that something is still wrong.

I also saw the deprecation warnings you pointed out, and they should be dealt with at some point before they become errors (but not here).

**Comment by hollyhan** [comment]
> @hollyhan I think I will hold off on merging this until you can try building the package again with this branch instead of master. It would be a pain to find out only after releasing the next version of `geometric_features` that something is still wrong.
> 
> I also saw the deprecation warnings you pointed out, and they should be dealt with at some point before they become errors (but not here).

The test script now works well with the right version of geometric_feature (0.6.0).  The PR is ready to be merged! 

plot_basins_ISMIP6_Basin

**Comment by matthewhoffman** [comment]
@xylar & @hollyhan , this is fantastic!  Thank you for getting this added and tested.

**Pull request merged**
