### PR TITLE
PEP8 cleanup and update to README.md

### PR DESCRIPTION
**Pull request by xylar**
Clean up PEP8 formatting of each script, driver script and utility file.

Update the README.md file to document (minimally) each script.

Remove the unused fix_features_at_prime_meridian.py script.

### CODE REVIEW

**Comment by xylar** [comment]
This PR is intended to address #54, #57 and #63.

**Comment by xylar** [comment]
### Testing

I ran all the manipulation script and verified (by opening or plotting each geojson file) that they produced the expected results.  Given that only formatting was being tested, the important thing is that they ran without errors.

**Comment by xylar** [comment]
@pwolfram, this should be an easy merge.  I think all you need to do is verify that you're okay with the update to the README (or suggest an alternative change) and make sure the basic workflow (merge, plot, split) works for you.

There's no rush on this one so get to it when you have a free moment.

**Comment by xylar** [comment]
@milenaveneziani, given that @pwolfram is pretty busy right now and that these changes are just cosmetic, would you be willing to review (and perhaps merge) this PR instead?

One check would be to make sure all the scripts in the main directory and in util are, in fact, PEP8 compliant.

I could also make the scripts in driver_scripts compliant if you would like.

**Comment by xylar** [comment]
I went ahead and did PEP8 (and a bit of other) clean up on the driver scripts.  I made sure all 3 that I modified run correctly.

**Comment by milenaveneziani** [comment]
@xylar: this looks good to me. I ran flake8 on all scripts, and the only error I got was a:
`E402 module level import not at top of file`
on plot_features for line 26-29, but I don't understand the reason (the module imports *are* at the top of the file..)

**Comment by xylar** [comment]
@milenaveneziani, yeah, there's nothing we can do about that.  It's complaining because, in the following lines:
```
 import matplotlib
 matplotlib.use('Agg')
 import matplotlib.pyplot as plt
```
We call a function (`matplotlib.use`) before an import.  But that's how `matplotlib` backends work.  There's no feasible way around it.

**Comment by xylar** [comment]
Thanks again, @milenaveneziani!

**Pull request merged**
