### PR TITLE
Add new Arctic critical passages and land blockages (plus Lombok St in Indonesian Throughflow)

### PR DESCRIPTION
**Pull request by milenaveneziani**
This adds the following new critical passages:
- Cardigan Strait in the Arctic Northwest Passages
- Akimiski Strait in Hudson Bay
- Disco Bay Channel along the western Greenland coast
- Lombok Strait (important channel within the Indonesian Throughflow, which should be open in our meshes, but better to enforce it)
- Qiongzhou Strait in the South China Sea (maybe better called Hainan Strait?)

and the following small land blockages (islands):
- Diomede Islands (Bering Strait)
- St Paul Island (Bering Sea)
- St George Island (Bering Sea)

### CODE REVIEW

**Comment by milenaveneziani** [comment]
**Testing**

In order to make sure that the small blockages are handled well at low-resolution, I am testing this with the 30to60 mesh.

**Comment by milenaveneziani** [comment]
Note: features were created separately with geojson.io and then properly processed for geometric_features following the developer documentation (which was *very* helpful).

**Review by xylar — APPROVED** [review]
@milenaveneziani, this looks great to me.  I'll test it along with https://github.com/MPAS-Dev/compass/pull/414

**Comment by xylar** [comment]
@milenaveneziani, keep me posted on how your testing goes in https://github.com/MPAS-Dev/compass/pull/414.  I can merge this an make a `geometric_features` release as soon as you're ready.

**Comment by xylar** [comment]
@milenaveneziani, I had the sense from Slack that you're ready for this to go in.  I hope that's correct because I'm going to go ahead.

**Comment by milenaveneziani** [comment]
yes, perfect. Thanks.

**Pull request merged**
