### PR TITLE
Additional projection types

### PR DESCRIPTION
**Pull request by pwolfram**
This PR cleans up the plotting routine and adds additional projection types

### CODE REVIEW

**Comment by pwolfram** [comment]
@xylar, here is the PR with some additional projections you can try out.

**Comment by xylar** [comment]
@pwolfram, thanks for looking into this.  I'll fulfill the PR as soon as I can find the time to do a proper test.

**Comment by xylar** [comment]
@pwolfram, thanks for these additional projections.  I think they will be useful.

I verified that all 5 new produce plots of features that look reasonable.  Here is an image with 4 of them with that Arctic and Southern Ocean:
test
I found a fix for the Arctic basin (first projecting the lat/lon coordinates to map coordinates, then plotting, rather than using the latlon flag), which I used here and I will make a PR for that change momentarily.

**Comment by xylar** [comment]
@pwolfram, I don't seem to have permission to delete your remote, so you will need to do that yourself.

**Comment by pwolfram** [comment]
Done, thanks @xylar!

**Pull request merged**
