### PR TITLE
Fix plotting of points

### PR DESCRIPTION
**Pull request by xylar**
Also, adjust standard figure size, dpi and some plotting properties for transects

### CODE REVIEW

**Comment by xylar** [comment]
This PR is intended to address #87

**Comment by xylar** [comment]
## Testing

```bash
./merge_features.py -d ocean/point/ -o points.geojson
./plot_features.py -f points.geojson
./driver_scripts/setup_ocean_standard_transport_sections.py 
./plot_features.py -f standard_transport_sections.geojson
```
(Examples here shortly...)

**Comment by xylar** [comment]
I just realized things aren't working for many of the point plots.  I'll keep working on this...

**Comment by pwolfram** [comment]
Verified that points, transects, and regions worked.

```
./merge_features.py -d ocean/region/Southern_Ocean/ -o SO.geojson
./plot_features.py -f SO.geojson 
```

Note, strange behavior with the moll projection because there is no green polygon-- @xylar, does a reason why this doesn't plot correctly immediately come to mind?  We may have a bug here because moll2 works.  Is so, I can open an issue.
so_moll2

so_moll

**Comment by xylar** [comment]
Thanks @pwolfram.  I'm not concerned about the moll plot.  There's something glitchy in cartopy we had a long discussion about it awhile ago.  But I just don't think we really need this particular projection to work.  One option would be to take it out (moll2 as well).

**Comment by pwolfram** [comment]
Forgot about https://github.com/MPAS-Dev/geometric_features/issues/53 and https://github.com/SciTools/cartopy/issues/802, thanks for reminding me!  I don't think we need to do anything on this right now unless we run the risk of being confusing by having moll and moll2, but this is low priority and not 100% clear to me.

**Pull request merged**
