### PR TITLE
Add Carroll Inlet as a critical passage

### PR DESCRIPTION
**Pull request by xylar**
This feature keeps access to Carroll Inlet adjacent to Stange Ice Shelf in the Bellingshausen Sea region of Antarctica.

image
image

### CODE REVIEW

**Comment by xylar** [comment]
Here's the image I used to identify the name of the inlet:
https://upload.wikimedia.org/wikipedia/commons/3/38/Bryan_Coast_to_Ellsworth_Land.jpg

**Review by darincomeau — APPROVED** [review]
Agree we want this open to avoid a land(-ice) locked ocean region - thanks @xylar !

**Comment by xylar** [comment]
My testing with this didn't work, but I found that the reason is that critical passages open up the ocean but don't change the `landIceFration` so the result is that a critical passage just changes grounded land-ice to floating land ice.  I'll need to fix that in Compass.

**Comment by xylar** [comment]
In my testing in https://github.com/MPAS-Dev/compass/pull/846, this seems to be accomplishing what we want it to.  If @darincomeau agrees, I'll merge both this PR and that one, and get to work on https://github.com/MPAS-Dev/compass/pull/845

**Comment by darincomeau** [comment]
Agree!

**Pull request merged**
