### PR TITLE
Add OSNAP sections to standard_transport_sections

### PR DESCRIPTION
**Pull request by milenaveneziani**
This adds two new transect features to `standard_transport_sections`: the OSNAP arrays West (Newfoundland to Greenland) and East (Greenland to Scotland). A plot of the transects is included below.
Screen Shot 2021-03-22 at 8 50 23 PM
Screen Shot 2021-03-22 at 8 50 05 PM

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@xylar: here are the transect additions we discussed over email. I think I have followed the correct workflow, but let me know if you have any comments. Thanks.

**Comment by milenaveneziani** [comment]
I decided to make a new tag for these sections: `arctic_sections`, so that we can make a separate arctic_sections file and not add these to the `standard_transport_sections` that we normally use for computing volume transport in MPAS-Analysis.

**Review by xylar — APPROVED** [review]
This looks great as well!

**Comment by milenaveneziani** [comment]
Thanks @xylar!

**Pull request merged**
