### PR TITLE
Update to v0.1.4

### PR DESCRIPTION
**Pull request by xylar**
In anticipation of a release

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, I'm about to make a release with 2 recent bug fixes.  This is because I'm building a new E3SM-Unified this week.

I assume it's okay if your work on the Arctic features (#118) waits for the next release.  Let me know, thought.

**Comment by milenaveneziani** [comment]
sure, no problem.

**Comment by milenaveneziani** [comment]
@xylar: I don't know how the process goes, but can you estimate when this release will be available through conda? I can  always use the local scripts, but  I thought it would be  better to use the conda package for the arctic feature script I am writing.

**Comment by xylar** [comment]
The process is:
* I make a release here
* A few hours later, a PR is automatically generated at the conda-forge feedstock: https://github.com/conda-forge/geometric_features-feedstock
* I wait for tests to pass, tweak the PR as needed and merge
* The files get uploaded to the conda-forge channel about 30 minutes later
* The files are recognized via `conda` anywhere from a few minutes to a few hours later

It should work already -- I've been using it in e3sm-unified testing.  Let me know if it doesn't.

**Pull request merged**
