### PR TITLE
Adds requirement for plot_features.py to README

### PR DESCRIPTION
**Pull request by pwolfram**
Fixes README and reduces ambiguity.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram, looks good.  It doesn't look like there's any easy way to make `plot_features.py` give its help message if `basemap` isn't present so I think this solution is fine.

**Comment by douglasjacobsen** [comment]
An easy way to catch if basemap isn't present is the following:

```
try:
    from mpl_toolkits.basemap import Basemap, addcyclic
except ImportError as e:
    print "ERROR: Cannot find either basemap or addcyclic. Error message follows:"
    print e
    sys.exit(1)
```

**Comment by xylar** [comment]
@douglasjacobsen, that would work but I think that's not really any more helpful than the default error message:
```
Traceback (most recent call last):
  File "./plot_features.py", line 19, in <module>
    from mpl_toolkits.basemap import Basemap, addcyclic
ImportError: No module named basemap
```
The main thing is not to tell people that they can find out the requirements by loading the help message, and then they find out that fails because they're missing the requirement.  This way, you don't expect to get that info from the help message, so it's okay.

**Comment by douglasjacobsen** [comment]
OK, sounds good.

**Pull request merged**
