### PR TITLE
Transition CI to GitHub Actions

### PR DESCRIPTION
**Pull request by altheaden**
In this PR I've transitioned the CI workflows from Azure Pipelines to GitHub Actions. This change makes geometric_features more in-line with related MPAS and E3SM repos, such as Polaris, Mache, and MPAS-Analysis.

### CODE REVIEW

**Comment by altheaden** [comment]
@xylar This was a pretty straightforward copy from the setup in MPAS-Analysis, so if there's anything specific to geometric_features that might be missing here just let me know and I can try to fix it.

**Comment by xylar** [comment]
I probably need to make several tweaks to the docs so they build with sphinx multiversion. I will at least try to do that here before we merge.

**Comment by altheaden** [comment]
Let me know if you need help with anything!

**Comment by xylar** [comment]
Okay, the second time seemed much easier than the first (on MPAS-Analysis) so I think I've got the docs sorted out in just 2 commits.

**Review by xylar — APPROVED** [review]
@altheaden, impeccable work as always! It looks ready to merge to me.

**Comment by xylar** [comment]
Yep, it worked like a charm!  The docs look good and all tests passed.

**Pull request merged**
