### PR TITLE
Changed feature's format for all features by running split_features

### PR DESCRIPTION
**Pull request by milenaveneziani**
The ocean/region/*geojson features now have the newer format. They were crated by running them through split_features.py.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram and @milenaveneziani, I would think this should be done for all features (i.e. all components, all points, transects and regions) in a single PR.  There could be multiple commits, one for each component.

**Comment by xylar** [comment]
@milenaveneziani and @pwolfram, I went ahead and pushed the reformatted feature files for the remaining features in the repo to this branch.  (It's taking a little while to upload on my relatively slow wifi but should be there soon.)

**Comment by milenaveneziani** [comment]
@xylar: do you think we can just merge this now using the Merge button?

**Comment by xylar** [comment]
@milenaveneziani, it might be best if we took the time to make sure we haven't broken anything first (e.g. but running some of the workflows that use geometric features).  Then, I think @pwolfram can just merge with the merge button.

**Comment by xylar** [comment]
The split needs to be redone as soon as #77 is merged.

**Comment by pwolfram** [comment]
@xylar, this is now ready to be redone.

**Comment by xylar** [comment]
Pushing this now.

**Comment by xylar** [comment]
@pwolfram, should be ready to merge.

**Comment by xylar** [comment]
@pwolfram, oops, hold off.  I didn't rebase first.  Give me a few minutes.

**Comment by xylar** [comment]
@pwolfram, okay I think I've done it correctly this time.

**Comment by pwolfram** [comment]
@xylar, this is great.  Thanks!

**Comment by pwolfram** [comment]
For the record, I checked that `split_features.py` didn't modify the file format for regions, transects, and points using the ocean files for input.  Files were bit for bit relative to repository ones.

**Pull request merged**
