### PR TITLE
Cleanup python tabs

### PR DESCRIPTION
**Pull request by douglasjacobsen**
This merge cleans up the python tabs and replaces them with 4 spaces. Additionally, it adds vim modelines to help keep this consistent formatting within the python scripts.

### CODE REVIEW

**Comment by douglasjacobsen** [comment]
@pwolfram You can also feel free to check this out too and provide feedback.

**Comment by pwolfram** [comment]
@douglasjacobsen, I just submitted a PR to your branch with the edits I would make https://github.com/douglasjacobsen/geometric_features/pull/1

**Comment by xylar** [comment]
@pwolfram's changes look good.  I'll bite my tongue and do my python coding in this repository with 4 spaces from now on.

**Comment by douglasjacobsen** [comment]
@xylar Since I'm using spaces, you better! :smile:

**Comment by douglasjacobsen** [comment]
BTW, I've pulled @pwolfram's PR into this one.

**Comment by xylar** [comment]
Looks good to me.

**Pull request merged**
